source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'AZWheelPickerView' do
  pod "AZWheelPickerView", :path => "../"
  
  target 'Tests' do
    pod 'FBSnapshotTestCase'
  end
end

